<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(NetVersion)</TargetFramework>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="$(DapperVersion)" />
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartFridgeApp.Shared\SmartFridgeApp.Shared.csproj" />
  </ItemGroup>
</Project>
