<Project>
	<PropertyGroup>
		<NetVersion>net10.0</NetVersion>
		<LangVersion>14</LangVersion>
		<Configurations>Debug;Release;Docker</Configurations>
		<AppVersion>0.9.0</AppVersion>
		<Authors>Dariusz Koziol</Authors>
		<Product>SmartFridgeApp</Product>
		<PackageProjectUrl>smartfridgeapp.pl</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Dariusz151/SmartFridgeApp</RepositoryUrl>
	</PropertyGroup>
	
	<PropertyGroup>
		<DapperVersion>2.1.66</DapperVersion>
		<NewtonsoftVersion>13.0.3</NewtonsoftVersion>
		<EntityFrameworkVersion>9.0.4</EntityFrameworkVersion>
		<NpgsqlVersion>9.0.4</NpgsqlVersion>
		<QuartzVersion>3.15.1</QuartzVersion>
		<SwashbuckleVersion>7.2.0</SwashbuckleVersion>
		<JwtBearerVersion>10.0.3</JwtBearerVersion>
		<GoogleAuthVersion>10.0.3</GoogleAuthVersion>
		<BCryptVersion>4.0.3</BCryptVersion>
		<MartenVersion>8.26.0</MartenVersion>
	</PropertyGroup>
	
	<PropertyGroup>
		<NUnitVersion>4.3.2</NUnitVersion>
		<NUnit3TestAdapterVersion>4.6.0</NUnit3TestAdapterVersion>
		<XUnitVersion>2.9.3</XUnitVersion>
		<MicrosoftNetTestSdkVersion>17.12.0</MicrosoftNetTestSdkVersion>
	</PropertyGroup>
	
</Project>