<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetVersion)</TargetFramework>
    <Configurations>$(Configuration)</Configurations>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Marten" Version="$(MartenVersion)" />
    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EntityFrameworkVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkVersion)" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(NpgsqlVersion)" />
    <PackageReference Include="BCrypt.Net-Next" Version="$(BCryptVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(EntityFrameworkVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\SmartFridgeApp.Core\SmartFridgeApp.Core.csproj" />
  </ItemGroup>
  
</Project>