services:
  smartfridgeapp:
    container_name: smartfridgeapp
    image: smartfridgeapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - SmartFridgeAppConnectionString__ConnectionString=Host=smartfridgeapp.db;Port=5432;Database=smartfridgeapp;Username=postgres;Password=postgres
    ports:
      - 8080:8080
    build:
      context: ../src/SmartFridgeApp.API
      dockerfile: Dockerfile
      args:
        - SOURCE=./obj/docker/publish
    depends_on:
      - smartfridgeapp.db
    networks:
      - smartfridgeapp-network

  smartfridgeapp.web:
    container_name: smartfridgeapp.web
    image: smartfridgeapp-web
    build:
      context: ../ui/SmartFridgeApp.Web/smartfridgeapp-web
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=http://localhost:8080
    ports:
      - 3000:80
    depends_on:
      - smartfridgeapp
    networks:
      - smartfridgeapp-network

networks:
  smartfridgeapp-network:
