services:
  smartfridgeapp.db:
    container_name: smartfridgeapp.db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartfridgeapp
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - smartfridgeapp-network

volumes:
  pgdata:

networks:
  smartfridgeapp-network:
