services:
  smartfridegeapp.test:
    container_name: smartfridgeapp.test
    image: smartfridgeapp.test
    environment:
      - SmartFridgeAppConnectionString=Host=smartfridgeapp.db;Port=5432;Database=smartfridgeapp;Username=postgres;Password=postgres
    ports:
      - "127.0.0.1:8082:8082"
    build:
      context: ../test/SmartFridgeApp.IntegrationTests
      dockerfile: Dockerfile.test
      args:
        - SOURCE=./obj/docker/publish
    depends_on:
      - smartfridgeapp.db
    networks:
      - smartfridgeapp-network

networks:
  smartfridgeapp-network:
