version: "3.9"

services:
  smartfridgeapp.sql:
    container_name: smartfridgeapp.sql
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "@Password"
    ports:
      - 1433:1433
    networks:
      - smartfridgeapp-network

networks:
  smartfridgeapp-network:
